<a href="https://colab.research.google.com/github/parksangau/colab/blob/main/0301_naver_finance_news_web_scraping_input_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 네이버 금융 뉴스기사 수집
* [삼성전자 : 네이버 금융](https://finance.naver.com/item/news.naver?code=005930)

```
<html lang="ko">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">
<title>네이버 금융</title>

<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20220511192542/css/newstock.css">
<style data-emotion="css" data-s=""></style>
</head>


<body>
<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20220511192542/js/jindo.min.ns.1.5.3.euckr.js"></script>
		<div class="tb_cont">
			<div class="tlline2">
				<strong><span class="red03">종목</span>뉴스</strong>
				<!-- [D] 선택시 blind 태그 추가 -->
				<div class="info_txt">종목뉴스 안내<a href="#" onclick="togglePannel('layer_section'); clickcr(this,'stn.ninfo','','',event); return false;" class="btn_info_layer"><img src="https://ssl.pstatic.net/static/nfinance/2017/10/13/btn_help2.png" alt="상세 설명"></a>
					<div class="layer_section" id="layer_section" style="display:none">
						<strong>네이버 증권 종목뉴스 안내</strong>
						<p class="txt">
							AI(인공지능 검색기술)을 이용한 종목 관련 뉴스입니다. <br>관련뉴스는 자동으로 묶어 보여줍니다.
							<br>
							<span class="txt_opt">
								검색영역 옵션
								<br>
								제목 : 제목에서 종목명이 검색된 결과입니다. <br>
								내용 : 제목과 본문에서 종목명이 검색된 결과입니다.
							</span>
						</p>
						<a href="#" onclick="togglePannel('layer_section'); return false;" class="btn_close"><span class="blind">닫기</span></a>
					</div>
				</div>
			</div>
			
			<table summary="종목뉴스의 제목, 정보제공, 날짜" cellspacing="0" class="type5">
				<caption>종목뉴스</caption>
				<colgroup>
					<col>
					<col width="130px">
					<col width="110px">
				</colgroup>
				<thead>
					<tr>
						<th scope="col">제목</th>
						<th scope="col">정보제공</th>
						<th scope="col">날짜</th>
					</tr>
				</thead>

		 		<tbody>
 							
 							<tr class="first">	 						
	 							<td class="title">
									<a href="/item/news_read.naver?article_id=0004836222&amp;office_id=014&amp;code=005930&amp;page=1&amp;sm=title_entity_id.basic" class="tit" onclick="clickcr(this,'stn.ntitclust','','',event);" target="_top">삼성, 포켓몬 이어 뚱랑이 갤Z플립3에 입힌다</a>
									
								</td>
								<td class="info">파이낸셜뉴스</td>
								<td class="date"> 2022.05.15 11:52</td>
 							</tr>	 					
 						

 							<tr>	 						
	 							<td class="title">
									<a href="/item/news_read.naver?article_id=0001990771&amp;office_id=016&amp;code=005930&amp;page=1&amp;sm=title_entity_id.basic" class="tit" onclick="clickcr(this,'stn.ntitclust','','',event);" target="_top">삼성전자, 16일부터 갤럭시 Z 플립3 '무직타이거 에디션' 한정 판매</a>
									
								</td>
								<td class="info">헤럴드경제</td>
								<td class="date"> 2022.05.15 11:41</td>
 							</tr>	 					
 				
				</tbody>
			</table>
 						
			<!--- 종목뉴스 끝--->
			<!--- 페이지 네비게이션 시작--->
			
			<table summary="페이지 네비게이션 리스트" class="Nnavi" align="center">
				<caption>페이지 네비게이션</caption>
				<tbody><tr>
					
						
		                
		                <td class="on">
				<a href="/item/news_news.nhn?code=005930&amp;page=1&amp;sm=title_entity_id.basic&amp;clusterId=" onclick="clickcr(this,'stn.npag','','',event);">1</a>
				</td>
                <td>
				<a href="/item/news_news.nhn?code=005930&amp;page=2&amp;sm=title_entity_id.basic&amp;clusterId=" onclick="clickcr(this,'stn.npag','','',event);">2</a>
				</td>
		                <td class="pgR">
				<a href="/item/news_news.nhn?code=005930&amp;page=11&amp;sm=title_entity_id.basic&amp;clusterId=" onclick="clickcr(this,'stn.npag','','',event);">
				다음<img src="https://ssl.pstatic.net/static/n/cmn/bu_pgarR.gif" width="3" height="5" alt="" border="0">
				</a>
				</td>

		                <td class="pgRR">
				<a href="/item/news_news.nhn?code=005930&amp;page=1269&amp;sm=title_entity_id.basic&amp;clusterId=" onclick="clickcr(this,'stn.npag','','',event);">맨뒤
				<img src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8" height="5" alt="" border="0">
				</a>
				</td>
		            
				</tr>
			</tbody></table>
            

	<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20220511192542/js/lcslog.js"></script>
</div>
</body>
</html>
```

## pandas만으로 데이터 수집하기

In [1]:
# pandas 불러오기
import pandas as pd
import numpy as np

## 검색 값 설정하기
* 웹사이트에서 검색한 URL 안에 우리의 검색어가 들어가 있습니다.
* 이렇게 검색어를 URL에 붙여서 넘기는 문구를 쿼리스트링이라고 부릅니다.
* 이 문자열을 검색어에 맞게 변경해 줍니다.
* 쿼리스트링 : 쿼리 문자열은 지정된 매개변수에 값을 할당하는 Uniform Resource Locator의 일부입니다. 쿼리 문자열에는 일반적으로 웹 브라우저나 기타 클라이언트 응용 프로그램에서 기본 URL에 추가한 필드가 포함됩니다.

<img src="https://media.vlpt.us/images/keywookim/post/d23e05e7-0cfb-4347-ab89-f1b8a3d170c8/creating_query_strings1.png">

In [2]:
print("https://finance.naver.com/item/news_news.nhn?code=005930&page=1&sm=title_entity_id.basic&clusterId=")

https://finance.naver.com/item/news_news.nhn?code=005930&page=1&sm=title_entity_id.basic&clusterId=

In [13]:
# 수집할 url을 가져옵니다.
item_code = "035420"
item_name = "NAVER"
page_no = 1

In [16]:
url = f"https://finance.naver.com/item/news_news.nhn?code={item_code}&page={page_no}&sm=title_entity_id.basic&clusterId="
print(url)

https://finance.naver.com/item/news_news.nhn?code=035420&page=1&sm=title_entity_id.basic&clusterId=

## read_html 로 수집하기
* 네이버 금융의 주가 기사를 read_html로 수집해서 table 이라는 변수에 담습니다.

In [17]:
# 수집결과 는 table이라는 변수에 담아주세요.

table = pd.read_html(url)
len(table)

5

In [22]:
# 페이징 테이블
table[-1]

   0   1   2   3   4   5   6   7   8   9   10  11
0   1   2   3   4   5   6   7   8   9  10  다음  맨뒤

In [23]:
# 맨 마지막 테이블인 페이징은 제외하고 하나의 데이터프레임으로 합치기
pd.concat(table[:-1])

,0,1,2,날짜,정보제공,제목
0,NaN,NaN,NaN,2022.08.24 10:30,파이낸셜뉴스,"“MZ 소상공인 위해” 네이버, ‘로컬 푸드 브랜드 스쿨’ 프로그램 진..."
1,NaN,NaN,NaN,2022.08.23 18:37,머니투데이,"탐앤탐스, '깔라만시 NFC 착즙주스' 등 네이버쇼핑 라이브서 판매"
2,NaN,NaN,NaN,2022.08.23 18:15,이데일리,“왜 핀테크만 원가 공개하나”…네이버·카카오·토스 100여곳 멘붕
3,NaN,NaN,NaN,2022.08.23 18:03,한국경제,"네이버 리셀 플랫폼 크림, 국내외 커머스 기업에 총 45억원 투자"
4,NaN,NaN,NaN,2022.08.23 15:50,이코노미스트,"코스피 이틀째 하락, 네이버·카카오 7거래일 연속↓ [마감시황]"
5,NaN,NaN,NaN,2022.08.23 14:58,매일경제,"매직에꼴, 네이버 웨일·포항테크노파크와 경북형 디지털 혁신 인재양성 위..."
6,NaN,NaN,NaN,2022.08.23 11:42,아시아경제,"""카카오·네이버가 보험까지 하냐"" 설계사들 거리로 나온 이유는"
7,NaN,NaN,NaN,2022.08.22 19:51,이데일리,"(영상)네이버 RE100 가입…""2040년까지 재생에너지로 100% 전..."
8,NaN,NaN,NaN,"연관기사 목록 네이버, 인터넷 기업 최초 'RE100' 가입 이데일리 2022...","연관기사 목록 네이버, 인터넷 기업 최초 'RE100' 가입 이데일리 2022...","연관기사 목록 네이버, 인터넷 기업 최초 'RE100' 가입 이데일리 2022..."
9,NaN,NaN,NaN,2022.08.22 12:03,이데일리,"네이버, 인터넷 기업 최초 'RE100' 가입"
10,NaN,NaN,NaN,2022.08.22 18:16,파이낸셜뉴스,"네이버 웨일, 충남교육청 손잡고 맞춤형 교육 조성"
11,NaN,NaN,NaN,"연관기사 목록 네이버, 충남교육청 등과 스마트 교육 활성화 이데일리 2022....","연관기사 목록 네이버, 충남교육청 등과 스마트 교육 활성화 이데일리 2022....","연관기사 목록 네이버, 충남교육청 등과 스마트 교육 활성화 이데일리 2022...."
12,NaN,NaN,NaN,2022.08.22 18:05,이데일리,"네이버, 충남교육청 등과 스마트 교육 활성화"
13,NaN,NaN,NaN,2022.08.22 13:41,파이낸셜뉴스,"네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색"
14,NaN,NaN,NaN,2022.08.22 18:08,파이낸셜뉴스,네이버 ‘RE100’ 가입… ESG경영 본격화
15,NaN,NaN,NaN,연관기사 목록 네이버 RE100 가입..“글로벌 ESG경영 본격화” 파이낸셜뉴스...,연관기사 목록 네이버 RE100 가입..“글로벌 ESG경영 본격화” 파이낸셜뉴스...,연관기사 목록 네이버 RE100 가입..“글로벌 ESG경영 본격화” 파이낸셜뉴스...
16,NaN,NaN,NaN,2022.08.22 10:42,파이낸셜뉴스,네이버 RE100 가입..“글로벌 ESG경영 본격화”
0,"네이버, 인터넷 기업 최초 'RE100' 가입",이데일리,2022.08.22 12:03,NaN,NaN,NaN
0,"네이버, 충남교육청 등과 스마트 교육 활성화",이데일리,2022.08.22 18:05,NaN,NaN,NaN
1,"네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색",파이낸셜뉴스,2022.08.22 13:41,NaN,NaN,NaN
0,네이버 RE100 가입..“글로벌 ESG경영 본격화”,파이낸셜뉴스,2022.08.22 10:42,NaN,NaN,NaN

## 데이터프레임으로 만들기
* 위에서 수집한 결과 중 table 변수 안에 있는 0번째 인덱스 값을 가져와서 df 라는 변수에 담아주세요.

In [ ]:
# table의 0번째 인덱스 값을 df 라는 변수에 담습니다.
# df

## 반복문으로 데이터 모두 가져오기
* for 문을 사용해 table 이라는 변수 안에 있는 값을 모두 가져오기
* temp_list 에 수집한 값을 담아주세요.

In [24]:
table[0].columns

Index(['제목', '정보제공', '날짜'], dtype='object')

In [25]:
table[1].columns

Int64Index([0, 1, 2], dtype='int64')

In [26]:
# 컬럼명 확인
table[1].columns = table[0].columns
table[1]

                          제목  정보제공                날짜
0  네이버, 인터넷 기업 최초 'RE100' 가입  이데일리  2022.08.22 12:03

In [27]:
table[2]

                                   0       1                 2
0           네이버, 충남교육청 등과 스마트 교육 활성화    이데일리  2022.08.22 18:05
1  네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색  파이낸셜뉴스  2022.08.22 13:41

In [31]:
table[2].columns = table[0].columns
table[2]

                                  제목    정보제공                날짜
0           네이버, 충남교육청 등과 스마트 교육 활성화    이데일리  2022.08.22 18:05
1  네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색  파이낸셜뉴스  2022.08.22 13:41

In [32]:
# 마지막 인덱스에는 페이지 번호가 들어있어서 제외합니다.
# 컬럼명을 첫번째 데이터프레임의 컬럼명으로 변경합니다.
temp_list = []
cols = table[0].columns
for news in table[:-1]:
    news.columns = cols
    temp_list.append(news)
    display(news)

,제목,정보제공,날짜
0,"“MZ 소상공인 위해” 네이버, ‘로컬 푸드 브랜드 스쿨’ 프로그램 진...",파이낸셜뉴스,2022.08.24 10:30
1,"탐앤탐스, '깔라만시 NFC 착즙주스' 등 네이버쇼핑 라이브서 판매",머니투데이,2022.08.23 18:37
2,“왜 핀테크만 원가 공개하나”…네이버·카카오·토스 100여곳 멘붕,이데일리,2022.08.23 18:15
3,"네이버 리셀 플랫폼 크림, 국내외 커머스 기업에 총 45억원 투자",한국경제,2022.08.23 18:03
4,"코스피 이틀째 하락, 네이버·카카오 7거래일 연속↓ [마감시황]",이코노미스트,2022.08.23 15:50
5,"매직에꼴, 네이버 웨일·포항테크노파크와 경북형 디지털 혁신 인재양성 위...",매일경제,2022.08.23 14:58
6,"""카카오·네이버가 보험까지 하냐"" 설계사들 거리로 나온 이유는",아시아경제,2022.08.23 11:42
7,"(영상)네이버 RE100 가입…""2040년까지 재생에너지로 100% 전...",이데일리,2022.08.22 19:51
8,"연관기사 목록 네이버, 인터넷 기업 최초 'RE100' 가입 이데일리 2022...","연관기사 목록 네이버, 인터넷 기업 최초 'RE100' 가입 이데일리 2022...","연관기사 목록 네이버, 인터넷 기업 최초 'RE100' 가입 이데일리 2022..."
9,"네이버, 인터넷 기업 최초 'RE100' 가입",이데일리,2022.08.22 12:03
10,"네이버 웨일, 충남교육청 손잡고 맞춤형 교육 조성",파이낸셜뉴스,2022.08.22 18:16
11,"연관기사 목록 네이버, 충남교육청 등과 스마트 교육 활성화 이데일리 2022....","연관기사 목록 네이버, 충남교육청 등과 스마트 교육 활성화 이데일리 2022....","연관기사 목록 네이버, 충남교육청 등과 스마트 교육 활성화 이데일리 2022...."
12,"네이버, 충남교육청 등과 스마트 교육 활성화",이데일리,2022.08.22 18:05
13,"네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색",파이낸셜뉴스,2022.08.22 13:41
14,네이버 ‘RE100’ 가입… ESG경영 본격화,파이낸셜뉴스,2022.08.22 18:08
15,연관기사 목록 네이버 RE100 가입..“글로벌 ESG경영 본격화” 파이낸셜뉴스...,연관기사 목록 네이버 RE100 가입..“글로벌 ESG경영 본격화” 파이낸셜뉴스...,연관기사 목록 네이버 RE100 가입..“글로벌 ESG경영 본격화” 파이낸셜뉴스...
16,네이버 RE100 가입..“글로벌 ESG경영 본격화”,파이낸셜뉴스,2022.08.22 10:42

                          제목  정보제공                날짜
0  네이버, 인터넷 기업 최초 'RE100' 가입  이데일리  2022.08.22 12:03

                                  제목    정보제공                날짜
0           네이버, 충남교육청 등과 스마트 교육 활성화    이데일리  2022.08.22 18:05
1  네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색  파이낸셜뉴스  2022.08.22 13:41

                              제목    정보제공                날짜
0  네이버 RE100 가입..“글로벌 ESG경영 본격화”  파이낸셜뉴스  2022.08.22 10:42

## 수집한 데이터 하나의 데이터프레임으로 합치기

<img src="https://pandas.pydata.org/docs/_images/merging_concat_basic.png">

* [Merge, join, concatenate and compare documentation](https://pandas.pydata.org/docs/user_guide/merging.html#merge-join-concatenate-and-compare)

* concat :  
    * axis=0 행을 기준으로 위아래로 같은 컬럼끼리 값을 이어 붙여 새로운 행을 만듦
    * axis=1 컬럼을 기준으로 인덱스가 같은 값을 옆으로 붙여 새로운 컬럼을 만듦

In [30]:
# pd.concat
# (shift + tab)
df_temp = pd.concat(temp_list)
df_temp

,제목,정보제공,날짜
0,"“MZ 소상공인 위해” 네이버, ‘로컬 푸드 브랜드 스쿨’ 프로그램 진...",파이낸셜뉴스,2022.08.24 10:30
1,"탐앤탐스, '깔라만시 NFC 착즙주스' 등 네이버쇼핑 라이브서 판매",머니투데이,2022.08.23 18:37
2,“왜 핀테크만 원가 공개하나”…네이버·카카오·토스 100여곳 멘붕,이데일리,2022.08.23 18:15
3,"네이버 리셀 플랫폼 크림, 국내외 커머스 기업에 총 45억원 투자",한국경제,2022.08.23 18:03
4,"코스피 이틀째 하락, 네이버·카카오 7거래일 연속↓ [마감시황]",이코노미스트,2022.08.23 15:50
5,"매직에꼴, 네이버 웨일·포항테크노파크와 경북형 디지털 혁신 인재양성 위...",매일경제,2022.08.23 14:58
6,"""카카오·네이버가 보험까지 하냐"" 설계사들 거리로 나온 이유는",아시아경제,2022.08.23 11:42
7,"(영상)네이버 RE100 가입…""2040년까지 재생에너지로 100% 전...",이데일리,2022.08.22 19:51
8,"연관기사 목록 네이버, 인터넷 기업 최초 'RE100' 가입 이데일리 2022...","연관기사 목록 네이버, 인터넷 기업 최초 'RE100' 가입 이데일리 2022...","연관기사 목록 네이버, 인터넷 기업 최초 'RE100' 가입 이데일리 2022..."
9,"네이버, 인터넷 기업 최초 'RE100' 가입",이데일리,2022.08.22 12:03
10,"네이버 웨일, 충남교육청 손잡고 맞춤형 교육 조성",파이낸셜뉴스,2022.08.22 18:16
11,"연관기사 목록 네이버, 충남교육청 등과 스마트 교육 활성화 이데일리 2022....","연관기사 목록 네이버, 충남교육청 등과 스마트 교육 활성화 이데일리 2022....","연관기사 목록 네이버, 충남교육청 등과 스마트 교육 활성화 이데일리 2022...."
12,"네이버, 충남교육청 등과 스마트 교육 활성화",이데일리,2022.08.22 18:05
13,"네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색",파이낸셜뉴스,2022.08.22 13:41
14,네이버 ‘RE100’ 가입… ESG경영 본격화,파이낸셜뉴스,2022.08.22 18:08
15,연관기사 목록 네이버 RE100 가입..“글로벌 ESG경영 본격화” 파이낸셜뉴스...,연관기사 목록 네이버 RE100 가입..“글로벌 ESG경영 본격화” 파이낸셜뉴스...,연관기사 목록 네이버 RE100 가입..“글로벌 ESG경영 본격화” 파이낸셜뉴스...
16,네이버 RE100 가입..“글로벌 ESG경영 본격화”,파이낸셜뉴스,2022.08.22 10:42
0,"네이버, 인터넷 기업 최초 'RE100' 가입",이데일리,2022.08.22 12:03
0,"네이버, 충남교육청 등과 스마트 교육 활성화",이데일리,2022.08.22 18:05
1,"네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색",파이낸셜뉴스,2022.08.22 13:41
0,네이버 RE100 가입..“글로벌 ESG경영 본격화”,파이낸셜뉴스,2022.08.22 10:42

## 위에서 수집한 데이터에서 결측치를 제거합니다.

In [34]:
# dropna
# 모든 데이터가 결측치 일 때 해당 컬럼을 지운다는 의미입니다. axis=0 은 행의 값이 모두 결측치 일때 해당 행을 지운다는 의미입니다.
df_temp.dropna()
df_temp

,제목,정보제공,날짜
0,"“MZ 소상공인 위해” 네이버, ‘로컬 푸드 브랜드 스쿨’ 프로그램 진...",파이낸셜뉴스,2022.08.24 10:30
1,"탐앤탐스, '깔라만시 NFC 착즙주스' 등 네이버쇼핑 라이브서 판매",머니투데이,2022.08.23 18:37
2,“왜 핀테크만 원가 공개하나”…네이버·카카오·토스 100여곳 멘붕,이데일리,2022.08.23 18:15
3,"네이버 리셀 플랫폼 크림, 국내외 커머스 기업에 총 45억원 투자",한국경제,2022.08.23 18:03
4,"코스피 이틀째 하락, 네이버·카카오 7거래일 연속↓ [마감시황]",이코노미스트,2022.08.23 15:50
5,"매직에꼴, 네이버 웨일·포항테크노파크와 경북형 디지털 혁신 인재양성 위...",매일경제,2022.08.23 14:58
6,"""카카오·네이버가 보험까지 하냐"" 설계사들 거리로 나온 이유는",아시아경제,2022.08.23 11:42
7,"(영상)네이버 RE100 가입…""2040년까지 재생에너지로 100% 전...",이데일리,2022.08.22 19:51
8,"연관기사 목록 네이버, 인터넷 기업 최초 'RE100' 가입 이데일리 2022...","연관기사 목록 네이버, 인터넷 기업 최초 'RE100' 가입 이데일리 2022...","연관기사 목록 네이버, 인터넷 기업 최초 'RE100' 가입 이데일리 2022..."
9,"네이버, 인터넷 기업 최초 'RE100' 가입",이데일리,2022.08.22 12:03
10,"네이버 웨일, 충남교육청 손잡고 맞춤형 교육 조성",파이낸셜뉴스,2022.08.22 18:16
11,"연관기사 목록 네이버, 충남교육청 등과 스마트 교육 활성화 이데일리 2022....","연관기사 목록 네이버, 충남교육청 등과 스마트 교육 활성화 이데일리 2022....","연관기사 목록 네이버, 충남교육청 등과 스마트 교육 활성화 이데일리 2022...."
12,"네이버, 충남교육청 등과 스마트 교육 활성화",이데일리,2022.08.22 18:05
13,"네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색",파이낸셜뉴스,2022.08.22 13:41
14,네이버 ‘RE100’ 가입… ESG경영 본격화,파이낸셜뉴스,2022.08.22 18:08
15,연관기사 목록 네이버 RE100 가입..“글로벌 ESG경영 본격화” 파이낸셜뉴스...,연관기사 목록 네이버 RE100 가입..“글로벌 ESG경영 본격화” 파이낸셜뉴스...,연관기사 목록 네이버 RE100 가입..“글로벌 ESG경영 본격화” 파이낸셜뉴스...
16,네이버 RE100 가입..“글로벌 ESG경영 본격화”,파이낸셜뉴스,2022.08.22 10:42
0,"네이버, 인터넷 기업 최초 'RE100' 가입",이데일리,2022.08.22 12:03
0,"네이버, 충남교육청 등과 스마트 교육 활성화",이데일리,2022.08.22 18:05
1,"네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색",파이낸셜뉴스,2022.08.22 13:41
0,네이버 RE100 가입..“글로벌 ESG경영 본격화”,파이낸셜뉴스,2022.08.22 10:42

## 네이버 수집한 기사에서 "제목"에 "연관기사"가 들어가는 데이터를 제거합니다.

* <font color="red">.str.contains 를 사용하며 조건의 반대에는 앞에 ~ 표시로 표현할 수 있습니다.</red>

In [35]:
~pd.Series([True])

0    False
dtype: bool

In [36]:
df_temp[~df_temp["제목"].str.contains("연관기사")]

                                            제목    정보제공                날짜
0   “MZ 소상공인 위해” 네이버, ‘로컬 푸드 브랜드 스쿨’ 프로그램 진...  파이낸셜뉴스  2022.08.24 10:30
1        탐앤탐스, '깔라만시 NFC 착즙주스' 등 네이버쇼핑 라이브서 판매   머니투데이  2022.08.23 18:37
2         “왜 핀테크만 원가 공개하나”…네이버·카카오·토스 100여곳 멘붕    이데일리  2022.08.23 18:15
3         네이버 리셀 플랫폼 크림, 국내외 커머스 기업에 총 45억원 투자    한국경제  2022.08.23 18:03
4          코스피 이틀째 하락, 네이버·카카오 7거래일 연속↓ [마감시황]  이코노미스트  2022.08.23 15:50
5   매직에꼴, 네이버 웨일·포항테크노파크와 경북형 디지털 혁신 인재양성 위...    매일경제  2022.08.23 14:58
6           "카카오·네이버가 보험까지 하냐" 설계사들 거리로 나온 이유는   아시아경제  2022.08.23 11:42
7   (영상)네이버 RE100 가입…"2040년까지 재생에너지로 100% 전...    이데일리  2022.08.22 19:51
9                    네이버, 인터넷 기업 최초 'RE100' 가입    이데일리  2022.08.22 12:03
10                 네이버 웨일, 충남교육청 손잡고 맞춤형 교육 조성  파이낸셜뉴스  2022.08.22 18:16
12                    네이버, 충남교육청 등과 스마트 교육 활성화    이데일리  2022.08.22 18:05
13           네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색  파이낸셜뉴스  2022.08.22 13:41
14                   네이버 ‘RE100’ 가입… ESG경영 본격화  파이낸셜뉴스  2022.08.22 18:08
16               네이버 RE100 가입..“글로벌 ESG경영 본격화”  파이낸셜뉴스  2022.08.22 10:42
0                    네이버, 인터넷 기업 최초 'RE100' 가입    이데일리  2022.08.22 12:03
0                     네이버, 충남교육청 등과 스마트 교육 활성화    이데일리  2022.08.22 18:05
1            네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색  파이낸셜뉴스  2022.08.22 13:41
0                네이버 RE100 가입..“글로벌 ESG경영 본격화”  파이낸셜뉴스  2022.08.22 10:42

In [37]:
df_temp[df_temp["제목"].str.contains("연관기사") == False]

                                            제목    정보제공                날짜
0   “MZ 소상공인 위해” 네이버, ‘로컬 푸드 브랜드 스쿨’ 프로그램 진...  파이낸셜뉴스  2022.08.24 10:30
1        탐앤탐스, '깔라만시 NFC 착즙주스' 등 네이버쇼핑 라이브서 판매   머니투데이  2022.08.23 18:37
2         “왜 핀테크만 원가 공개하나”…네이버·카카오·토스 100여곳 멘붕    이데일리  2022.08.23 18:15
3         네이버 리셀 플랫폼 크림, 국내외 커머스 기업에 총 45억원 투자    한국경제  2022.08.23 18:03
4          코스피 이틀째 하락, 네이버·카카오 7거래일 연속↓ [마감시황]  이코노미스트  2022.08.23 15:50
5   매직에꼴, 네이버 웨일·포항테크노파크와 경북형 디지털 혁신 인재양성 위...    매일경제  2022.08.23 14:58
6           "카카오·네이버가 보험까지 하냐" 설계사들 거리로 나온 이유는   아시아경제  2022.08.23 11:42
7   (영상)네이버 RE100 가입…"2040년까지 재생에너지로 100% 전...    이데일리  2022.08.22 19:51
9                    네이버, 인터넷 기업 최초 'RE100' 가입    이데일리  2022.08.22 12:03
10                 네이버 웨일, 충남교육청 손잡고 맞춤형 교육 조성  파이낸셜뉴스  2022.08.22 18:16
12                    네이버, 충남교육청 등과 스마트 교육 활성화    이데일리  2022.08.22 18:05
13           네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색  파이낸셜뉴스  2022.08.22 13:41
14                   네이버 ‘RE100’ 가입… ESG경영 본격화  파이낸셜뉴스  2022.08.22 18:08
16               네이버 RE100 가입..“글로벌 ESG경영 본격화”  파이낸셜뉴스  2022.08.22 10:42
0                    네이버, 인터넷 기업 최초 'RE100' 가입    이데일리  2022.08.22 12:03
0                     네이버, 충남교육청 등과 스마트 교육 활성화    이데일리  2022.08.22 18:05
1            네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색  파이낸셜뉴스  2022.08.22 13:41
0                네이버 RE100 가입..“글로벌 ESG경영 본격화”  파이낸셜뉴스  2022.08.22 10:42

In [52]:
# df

## 위의 과정을 함수로 만듭니다.
* 빈칸을 완성해 수집한 table 을 넘겨주면 데이터프레임을 반환하는 함수를 완성해 주세요.

In [41]:
# get_url item_code, page_no 를 넘기면 url 을 반환하는 함수
def get_url(item_code, page_no):
    """
    item_code, page_no 를 넘기면 url 을 반환하는 함수
    """
    url = f"https://finance.naver.com/item/news_news.nhn?code={item_code}&page={page_no}&sm=title_entity_id.basic&clusterId="
    return url

In [53]:
page_no = 5
item_code = "035420"
temp_url = get_url(item_code, page_no)
print(temp_url)

https://finance.naver.com/item/news_news.nhn?code=035420&page=5&sm=title_entity_id.basic&clusterId=

In [44]:
get_url?

## 뉴스 한 페이지를 수집하는 함수
```
1) URL 을 받아옴
2) read_html 로 테이블 정보를 받아옴
3) 데이터프레임 컬럼명을 ["제목", "정보제공", "날짜"]로 변경
4) temp_list 에 데이터프레임을 추가
5) concat 으로 리스트 병합하여 하나의 데이터프레임으로 만들기
6) 결측치 제거
7) 연관기사 제거
8) 데이터프레임 반환
```

In [60]:
# get_one_page_news 함수 만들기
def get_one_page_news(item_code, page_no):  # 한 페이지씩 받아오는 함수
    """
    get_url 에 item_code, page_no 를 넘겨 url 을 받아오고
    뉴스 한 페이지를 수집하는 함수
    1) URL 을 받아옴
    2) read_html 로 테이블 정보를 받아옴
    3) 데이터프레임 컬럼명을 ["제목", "정보제공", "날짜"]로 변경
    4) temp_list 에 데이터프레임을 추가
    5) concat 으로 리스트 병합하여 하나의 데이터프레임으로 만들기
    6) 결측치 제거
    7) 연관기사 제거
    8) 데이터프레임 반환
    """
    temp_url = get_url(item_code, page_no)
    table = pd.read_html(url)
    temp_list = []
    cols = table[0].columns
    for news in table[:-1]:
        news.columns = cols
        temp_list.append(news)

    df_temp = pd.concat(temp_list)

    df = df_temp[~df_temp["제목"].str.contains("연관기사")]
    return df

* 아래 코드를 실행했을 때 수집된 데이터프레임이 출력된다면 잘 만들어진 것입니다.

In [61]:
page_no = 4

temp = get_one_page_news(item_code, page_no)
temp

                                            제목    정보제공                날짜
0   “MZ 소상공인 위해” 네이버, ‘로컬 푸드 브랜드 스쿨’ 프로그램 진...  파이낸셜뉴스  2022.08.24 10:30
1        탐앤탐스, '깔라만시 NFC 착즙주스' 등 네이버쇼핑 라이브서 판매   머니투데이  2022.08.23 18:37
2         “왜 핀테크만 원가 공개하나”…네이버·카카오·토스 100여곳 멘붕    이데일리  2022.08.23 18:15
3         네이버 리셀 플랫폼 크림, 국내외 커머스 기업에 총 45억원 투자    한국경제  2022.08.23 18:03
4          코스피 이틀째 하락, 네이버·카카오 7거래일 연속↓ [마감시황]  이코노미스트  2022.08.23 15:50
5   매직에꼴, 네이버 웨일·포항테크노파크와 경북형 디지털 혁신 인재양성 위...    매일경제  2022.08.23 14:58
6           "카카오·네이버가 보험까지 하냐" 설계사들 거리로 나온 이유는   아시아경제  2022.08.23 11:42
7   (영상)네이버 RE100 가입…"2040년까지 재생에너지로 100% 전...    이데일리  2022.08.22 19:51
9                    네이버, 인터넷 기업 최초 'RE100' 가입    이데일리  2022.08.22 12:03
10                 네이버 웨일, 충남교육청 손잡고 맞춤형 교육 조성  파이낸셜뉴스  2022.08.22 18:16
12                    네이버, 충남교육청 등과 스마트 교육 활성화    이데일리  2022.08.22 18:05
13           네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색  파이낸셜뉴스  2022.08.22 13:41
14                   네이버 ‘RE100’ 가입… ESG경영 본격화  파이낸셜뉴스  2022.08.22 18:08
16               네이버 RE100 가입..“글로벌 ESG경영 본격화”  파이낸셜뉴스  2022.08.22 10:42
0                    네이버, 인터넷 기업 최초 'RE100' 가입    이데일리  2022.08.22 12:03
0                     네이버, 충남교육청 등과 스마트 교육 활성화    이데일리  2022.08.22 18:05
1            네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색  파이낸셜뉴스  2022.08.22 13:41
0                네이버 RE100 가입..“글로벌 ESG경영 본격화”  파이낸셜뉴스  2022.08.22 10:42

## 반복문을 사용해 10페이지까지 수집
* 위에서 만든 함수를 활용합니다.
* time.sleep() 을 통해 데이터를 쉬었다 가져옵니다.

In [64]:
import time
from tqdm import trange

# page_no = 0
news_list = []
for page_no in trange(1, 11):
    temp = get_one_page_news(item_code, page_no)
    news_list.append(temp)
    time.sleep(1)

100%|██████████| 10/10 [00:18<00:00,  1.85s/it]

## 위에서 수집한 데이터는 news_list 라는 변수에 들어있습니다. 판다스를 활용해 하나의 데이터프레임으로 만들어 주세요.

* concat :  
    * axis=0 행을 기준으로 위아래로 같은 컬럼끼리 값을 이어 붙여 새로운 행을 만듦
    * axis=1 컬럼을 기준으로 인덱스가 같은 값을 옆으로 붙여 새로운 컬럼을 만듦

In [67]:
# 1) 데이터 프레임 하나로 합치고 인덱스 번호가 제각각인것을 볼 수 있습니다.
# 2) reset_index() 를 하면 기존 인덱스가 index 컬럼으로 생기고 새로운 인덱스가 생깁니다.
# 3) reset_index(drop=True) 기존 인덱스를 제거하고 새로 생성한 인덱스만 남깁니다.
# df_news
df_news = pd.concat(news_list).reset_index(drop=True)
df_news

                                             제목    정보제공                날짜
0    “MZ 소상공인 위해” 네이버, ‘로컬 푸드 브랜드 스쿨’ 프로그램 진...  파이낸셜뉴스  2022.08.24 10:30
1         탐앤탐스, '깔라만시 NFC 착즙주스' 등 네이버쇼핑 라이브서 판매   머니투데이  2022.08.23 18:37
2          “왜 핀테크만 원가 공개하나”…네이버·카카오·토스 100여곳 멘붕    이데일리  2022.08.23 18:15
3          네이버 리셀 플랫폼 크림, 국내외 커머스 기업에 총 45억원 투자    한국경제  2022.08.23 18:03
4           코스피 이틀째 하락, 네이버·카카오 7거래일 연속↓ [마감시황]  이코노미스트  2022.08.23 15:50
..                                          ...     ...               ...
175               네이버 RE100 가입..“글로벌 ESG경영 본격화”  파이낸셜뉴스  2022.08.22 10:42
176                   네이버, 인터넷 기업 최초 'RE100' 가입    이데일리  2022.08.22 12:03
177                    네이버, 충남교육청 등과 스마트 교육 활성화    이데일리  2022.08.22 18:05
178           네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색  파이낸셜뉴스  2022.08.22 13:41
179               네이버 RE100 가입..“글로벌 ESG경영 본격화”  파이낸셜뉴스  2022.08.22 10:42

[180 rows x 3 columns]

## 파일로 저장하기

<img src="https://pandas.pydata.org/docs/_images/02_io_readwrite.svg">

In [72]:
last_date = df_news.iloc[0]["날짜"].split()[0]
last_date

'2022.08.24'

In [77]:
item_name = "NAVER"
file_name = f"news-{item_name}-{item_code}-{last_date}.csv"
file_name

'news-NAVER-035420-2022.08.24.csv'

In [79]:
# to_csv
df_news.to_csv(file_name, index=False)

In [81]:
# read_csv
pd.read_csv(file_name)

                                             제목    정보제공                날짜
0    “MZ 소상공인 위해” 네이버, ‘로컬 푸드 브랜드 스쿨’ 프로그램 진...  파이낸셜뉴스  2022.08.24 10:30
1         탐앤탐스, '깔라만시 NFC 착즙주스' 등 네이버쇼핑 라이브서 판매   머니투데이  2022.08.23 18:37
2          “왜 핀테크만 원가 공개하나”…네이버·카카오·토스 100여곳 멘붕    이데일리  2022.08.23 18:15
3          네이버 리셀 플랫폼 크림, 국내외 커머스 기업에 총 45억원 투자    한국경제  2022.08.23 18:03
4           코스피 이틀째 하락, 네이버·카카오 7거래일 연속↓ [마감시황]  이코노미스트  2022.08.23 15:50
..                                          ...     ...               ...
175               네이버 RE100 가입..“글로벌 ESG경영 본격화”  파이낸셜뉴스  2022.08.22 10:42
176                   네이버, 인터넷 기업 최초 'RE100' 가입    이데일리  2022.08.22 12:03
177                    네이버, 충남교육청 등과 스마트 교육 활성화    이데일리  2022.08.22 18:05
178           네이버 웨일, 충남교육청과 ‘맞춤형 교육’ 지원 가능성 모색  파이낸셜뉴스  2022.08.22 13:41
179               네이버 RE100 가입..“글로벌 ESG경영 본격화”  파이낸셜뉴스  2022.08.22 10:42

[180 rows x 3 columns]